#!/bin/sh

buttonrc="/etc/rc.button"
if [ ! -L $buttonrc/rfkill ] || [ "$(readlink $buttonrc/rfkill)" != "rfkill.btnb" ]; then
	mv $buttonrc/rfkill $buttonrc/rfkill.owrt
	ln -s rfkill.btnb $buttonrc/rfkill
fi

[ -e /etc/config/button-bind ] || touch /etc/config/button-bind

exit 0
