#!/bin/sh

# remove old config for aptimeclock, is handled by config for radio0 now
if [ "$(uci get wireless.radio1.client_clock_on)" ]; then
	uci delete wireless.radio1.client_clock_on
fi
if [ "$(uci get wireless.radio1.client_clock_off)" ]; then
	uci delete wireless.radio1.client_clock_off
fi
