#!/usr/bin/lua

local sysconfig = require 'gluon.sysconfig'

if not sysconfig.gluon_version then
  local uci = require('simple-uci').cursor()
  local wifi_iface_types = {'client', 'mesh', 'ibss'}

  uci:foreach('wireless', 'wifi-device', function(config)
    local radio = config['.name']

    if config.hwmode == '11a' or config.hwmode == '11na' then
      for _, type in ipairs(wifi_iface_types) do
        if not uci:get('wireless', type .. '_' .. radio) then
          return
        end

        uci:set('wireless', type .. '_' .. radio, 'disabled', 1)
      end
    end
  end)

  uci:save('wireless')
end
